#+title: Lecture 1
#+author: Daniel Ballesteros-Chávez
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 26.1 (Org mode 9.3.6)
#+PROPERTY: header-args :R :exports both
#+PROPERTY: header-args :R :session *R*



* Introduction to R

- What is R?

R is an open source statistical software.

- How to get it?

You can get R directly on their website [[https://www.r-project.org/]]

- What is RStudio?

RStudio is an integrated development environment (IDE) for R.

It is a good tool to get started if you are not used to scripting
programming. It has very helpful visual features.

https://www.rstudio.com/

I use [[https://www.gnu.org/software/emacs/][emacs]] and it is difficult for me to get used to Rstudio. My
advice: use whatever you find more comfortable.



 + Basic commands
   + getwd()
   + setwd()
   + install.packages()
   + library()
   + df <- read.dbf()
   + df$NAME
   + dim(df)
   + class(df)
   + ls()
   + rm(list=ls())
   + sum(df$NAME)
   + as.numeric()
   + as.character()
   + df$NEWVAR <- df$NAME
   + table()
   + tapply, sapply, lapply, etc.

* Help and Documentation

The =help()= function and =?= help operator in R provide access to the
documentation pages for R functions, data sets, and other objects,
both for packages in the standard R distribution and for contributed
packages.

You may also use the =help()= function to access information about a
package in your library — for example, ~help(package="MASS")~

To access help for a function in a package that’s not currently
loaded, specify in addition the name of the package: For example, to
obtain documentation for the ~rlm()~ (robust linear model) function in
the MASS package, ~help(rlm, package="MASS")~.

You can read mor about getting help in 

https://www.r-project.org/help.html


* The Working Directory

Get my Working Directory (a.k.a. where am I?)
#+begin_example R
getwd()
#+end_example


Set my Working Directory (a.k.a. change directory)
#+begin_example R
setwd("/home/ennaniux/Documents/R_Modelling")
#+end_example

How does this work in Windows?
#+begin_example R
setwd("C:/home/ennaniux/Documents/R_Modelling")
#+end_example

or maybe 
#+begin_example R
setwd("C:\\home\\ennaniux\\Documents\\R_Modelling")
#+end_example


* Installing packages

The Packages are sets of tools that can be downloaded from different
servers around the world. Different packages have different R
functions for specific purposes.


The Comprehensive R Archive Network (CRAN)
https://cran.r-project.org/. CRAN is a network of ftp and web servers
around the world that store identical, up-to-date, versions of code
and documentation for R.

For example, the foreign package allows R to read different data set
files like .sav, .dbf, and other file extensions.

In order to install the package foreign we type in the console
#+begin_example R
install.packages("foreign")
#+end_example

this will provide a list of possible servers to choose from, and you
can select one close to your location.



* Simple manipulations; numbers and vectors

The simplest data structure R operates on is the *numeric vector*, which
is a single entity consisting of an ordered collection of numbers.

#+begin_src R :results value :exports both
x <- c(1,3,5,9)
x
#+end_src

#+RESULTS:
| 1 | 3 | 5 | 9 |

The syntax is equivalent to 
#+begin_src R :results value :exports both
c(11,31,15,19) -> y
y
#+end_src

#+RESULTS:
| 11 | 31 | 15 | 19 |

and 
#+begin_src R :results value :exports both
assign("z",c(-1,33,2.5,9) )
z
#+end_src

#+RESULTS:
| -1 | 33 | 2.5 | 9 |


Linear operations:
#+begin_src R :results value :exports both
z * y + x
#+end_src

#+RESULTS:
| -10 | 1026 | 42.5 | 180 |

Definition of a sequence
#+begin_src R :results value :exports both
3:10
#+end_src

#+RESULTS:
| 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |

If we want to know the number of entries in our vector, then we use the function =length=
#+begin_src R :results value :exports both
length(c(3:10))
#+end_src

#+RESULTS:
: 8

If we want to know what value is in the i-th position we use square brackets
#+begin_src R :results value :exports both
x <- c("Uno", "Dos", NA, "Cuatro", "Dos", "Cuatro")
x[5]
#+end_src

#+RESULTS:
: Dos

R tries to apply operations on vectors
#+begin_src R :results value :exports both
x <- c(3:10)
x^2
#+end_src

#+RESULTS:
| 9 | 16 | 25 | 36 | 49 | 64 | 81 | 100 |

The sum of the first 100 natural numbers, if we want to perform the sum

#+html: <a href="https://www.codecogs.com/eqnedit.php?latex=\Large{\color{DarkBlue}&space;\sum_{k=1}^{100}&space;k&space;}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\Large{\color{DarkBlue}&space;\sum_{k=1}^{100}&space;k&space;}" title="\Large{\color{DarkBlue} \sum_{k=1}^{100} k }" /></a>

one can do for instance
#+begin_src R :results value :exports both
x <- c(1:100)
sum(x)
#+end_src

#+RESULTS:
: 5050


Missing values are denoted by =NA=. Whenever there is a missing value, the default behaviour is to be reminded:
#+begin_src R :results value :exports both
x <- c(4, 4, NA, 2, 3, NA, 5)
sum(x)
#+end_src

#+RESULTS:
: nil

Then, if you want to omit the missing values in the operation you have to specify it
#+begin_src R :results value :exports both
x <- c(4, 4, NA, 2, 3, NA, 5)
sum(x, na.rm=TRUE)
#+end_src

#+RESULTS:
: 18

A vector can also consists of strings or character type entries:
#+begin_src R :results value :exports both
x <- c("Uno", "Dos", NA, "Cuatro", "Dos", "Cuatro")
unique(x)
#+end_src

#+RESULTS:
| Uno | Dos | nil | Cuatro |


How do we know if ther are missing values?
#+begin_src R :results value :exports both
x <- c(4, 4, NA, 2, 3, NA, 5)
is.na(x)
#+end_src

#+RESULTS:
| FALSE | FALSE | TRUE | FALSE | FALSE | TRUE | FALSE |



* Pre-loaded data

In R there are several pre-loaded data

#+begin_src R :exports both :colnames yes
## In case the code below does not work
## you may need to install the package dataset
## For a list of available  datasets, type library(help = "datasets")
head(iris)
#+end_src

#+RESULTS:
| Sepal.Length | Sepal.Width | Petal.Length | Petal.Width | Species |
|--------------+-------------+--------------+-------------+---------|
|          5.1 |         3.5 |          1.4 |         0.2 | setosa  |
|          4.9 |           3 |          1.4 |         0.2 | setosa  |
|          4.7 |         3.2 |          1.3 |         0.2 | setosa  |
|          4.6 |         3.1 |          1.5 |         0.2 | setosa  |
|            5 |         3.6 |          1.4 |         0.2 | setosa  |
|          5.4 |         3.9 |          1.7 |         0.4 | setosa  |


We can also obtain a summary of the data set
#+begin_src R :exports both :colnames yes
summary(iris)
#+end_src

#+RESULTS:
| Sepal.Length  | Sepal.Width   | Petal.Length  | Petal.Width   | Species       |
|---------------+---------------+---------------+---------------+---------------|
| Min.   :4.300 | Min.   :2.000 | Min.   :1.000 | Min.   :0.100 | setosa    :50 |
| 1st Qu.:5.100 | 1st Qu.:2.800 | 1st Qu.:1.600 | 1st Qu.:0.300 | versicolor:50 |
| Median :5.800 | Median :3.000 | Median :4.350 | Median :1.300 | virginica :50 |
| Mean   :5.843 | Mean   :3.057 | Mean   :3.758 | Mean   :1.199 | nil           |
| 3rd Qu.:6.400 | 3rd Qu.:3.300 | 3rd Qu.:5.100 | 3rd Qu.:1.800 | nil           |
| Max.   :7.900 | Max.   :4.400 | Max.   :6.900 | Max.   :2.500 | nil           |



* Writing a data frame

Write a data frame by specifying the columns:

#+begin_src R :exports both :colnames yes
df <- data.frame(
"NAME" =  c("Aleksandra", "Hugo", "Piotr", "Ewa"),
"AGE"  =  c(29,35, 39, 33),
"HEIGHT"= c(1.68, 1.83, 2.03, 1.66) )
df
#+end_src

#+RESULTS:
| NAME       | AGE | HEIGHT |
|------------+-----+--------|
| Aleksandra |  29 |   1.68 |
| Hugo       |  35 |   1.83 |
| Piotr      |  39 |   2.03 |
| Ewa        |  33 |   1.66 |


What is the dimension of the data frame?
#+begin_src R 
dim(df)
#+end_src

#+RESULTS:
| 4 | 3 |

What are the variable names of the data frame?
#+begin_src R 
names(df)
#+end_src

#+RESULTS:
| NAME | AGE | HEIGHT |



* Reading a data frame

From a .csv file

#+begin_example R
df <- read.csv('./path_to/file.csv')
#+end_example

From a .dbf file
#+begin_example R
library(foreign)
df <- read.csv('./path/to/file.dbf')
#+end_example

From a .sav file
#+begin_example R
library(foreign)
     df <- read.spss(file='./path/to/file.sav', to.data.frame=TRUE) 
     str(df)   # show the structure of the data frame
#+end_example

From the clipboard
#+begin_example R
df2 <- read.table(file = "clipboard", sep = "\t", header=TRUE)
#+end_example


* Operations with data frames

Select a column/field/variable from a data frame
#+begin_src R :exports both :colnames yes
df <- iris
head(df$Species)
#+end_src

#+RESULTS:
| x      |
|--------|
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |


A table of frequences for a variable in a data frame 
#+begin_src R :exports both :colnames yes
df <- iris
table(df$Species)
#+end_src

#+RESULTS:
| Var1       | Freq |
|------------+------|
| setosa     |   50 |
| versicolor |   50 |
| virginica  |   50 |




