#+options: ':nil *:t -:t ::t <:t H:1 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:nil todo:t |:t
#+title:  Hypotesis test
#+date: 
#+author: Daniel Ballesteros-Chávez
#+email: danielyho@yahoo.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 26.1 (Org mode 9.3.6)
#+latex_class: beamer
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:

#+columns: %45ITEM %10BEAMER_env(Env) %10BEAMER_act(Act) %4BEAMER_col(Col) %8BEAMER_opt(Opt)
#+beamer_theme:  madrid
#+beamer_color_theme: structure
#+beamer_font_theme:
#+beamer_inner_theme:
#+beamer_outer_theme:
#+beamer_header: \usepackage{graphicx}
#+beamer_header: \institute[SUT]{\includegraphics[width=4cm]{/home/daniel/Pictures/Logos/politechnika_sl_logo_poziom_pl_rgb.png} \\  Silesian University of Technology \\ (Politechnika Śląska)}
#+beamer_header: \title{Hypotesis test.}
#+beamer_header: \author[D. Ballesteros]{Daniel Ballesteros Ch\'avez}

# \setbeamertemplate{background}[grid]

* 
* Introduction

The goal of hypothesis testing is to assess the evidence provided by the data in favour of some claim
about the population parameters. 


The hypothesis is a statement about a population parameter.
The first step of hypothesis testing is to formulate hypothesis statements - the null hypothesis and
alternative hypothesis.


* Hypotesis

*The null hypothesis*, denoted $H_0$ , is a statement of no effect or no difference. When performing
the hypothesis test, we assess the strength of evidence against the null hypothesis.

*The alternative hypothesis*, denoted $H_1$ is the statement that we suspect is true instead of $H_0$ . If
there is evidence against $H_0$ , then we may conclude that there is evidence for H_1 as the statement
explaining our parameter. $H_1$ is usually a statement of a difference.

** 

A *one-sided* or one-tailed test – the population parameter differs from its hypothesised value in
a specific direction, that is the parameter is either larger or smaller than the hypothesised value.


A *two-sided* or two-tailed test – the population parameter is different from the hypothesised
value; the direction is not specified.

* Example

Formulate the null and alternative hypotheses for the following research question: Is the
average monthly rent of a one-bedroom flat in Gliwice more than PLN 600?


Denote the mean monthly rent of all one-bedroom flats in Gliwice by $\mu$. We are comparing $\mu$ to
the value of PLN 600, and we are interested whether $\mu$ is larger than PLN 600, so it is an one-sided test.
Our hypotheses are:
\begin{equation}
H_0 : \mu = 600 , \qquad H_1 : \mu > 600
\end{equation}


* Test statistic

The test statistic is a random variable with a known distribution and will depend on the type of
statistical test we are carrying out.


In practice, we collect the data and we calculate the value of test statistic for the specific data sample,
using a formula.

* Z-test

The test statistic for one of the most common tests, Z-test, is given by
\begin{equation}
Z = \frac{\hat{\theta} - \mu_0}{\sigma/\sqrt{n}},
\end{equation}

where $\mu_0$ is the value of the hypothesised population mean. We have already proven that
$Z \sim N(0,1)$.

Note: The test statistic is based on the statistic that estimates the parameter that appears in the hypotheses.
E.g. in the example above $\hat{\theta}$ estimates $\mu_0$.

* Assessing our estimate

To assess how far the estimate is from the parameter, we standardise the estimate. So, the test
statistics are commonly in the form
\begin{equation}
\frac{\sigma_{\hat{\theta}}}{\hat{\theta}}
\end{equation}


* p- Value

The test statistic is used for the probability calculation which indicates the strength of evidence
against $H_0$ , so called p-value.


Definition of p-value: The p-value of a test is the probability, assuming $H_0$ is true, that we
would obtain a value of our test statistic as extreme or more extreme than the one we have observed.

* Interpretation

Extreme here means ‘far from what we expect’, assuming $H_0$ is true. The direction counting as ‘far
from what we expect’ is determined by $H_1$ .
\vspace{1cm}

The smaller the p-value we get, the stronger the evidence against $H_0$ we have, given by
our data.
\vspace{1cm}


In many disciplines, the p-value is then compared to the significance level of the test.
The significance level, denoted by $\alpha$, can be thought of as an evidence threshold.


* General rules (for all hypothesis tests):

+ If the p-value is less or equal to this threshold, that is p ≤ α,
  then we reject the null hypothesis $H_0$ at $\alpha$ and there is
  evidence to support the alternative hypothesis $H_1$ , based on our
  data.
+ If $p > \alpha$, then we fail to reject $H_0$ at $\alpha$ and there
  is not enough evidence to support $H_1$ , based on our data.

* Summary

+ State the null and alternative hypotheses.
+ Calculate the value of the test statistic.
+ Find a p-value for the test.
+ Decide whether to reject or not to reject the null hypothesis at the significance level $\alpha$.


* Remarks


When we reject $H_0$, it does not mean that it is not true, it just means that based on our data, we
found evidence against $H_0$ and so, in turn, we have evidence to support $H_1$.
\vspace{0.5cm}


Similarly, if we fail to reject $H_0$ , it does not make $H_0$ necessarily true, it just means that based on
our data, we do not have enough evidence against $H_0$.
\vspace{0.5cm}


When interpreting results practically, we usually do so with respect to the alternative hypothesis.


* Example

Cholesterol level in a particular population was known to have a mean value $\mu = 170$
in the past. We also know that the population standard deviation of the cholesterol is $\sigma = 30$.
A random sample of $n = 20$ people was taken and their sample mean was $185$. 

Perform a Z-test to determine whether there is evidence that the population mean has increased. Test at the 5%
significance level.

* Solution

Since $p = 0.01255 < 0.05$, we reject $H_0$ at the 5% level. We can conclude that there is evidence that
the mean cholesterol level has increased from $170$.


* Strength of the evidence

Even though in many disciplines, the significance level α is decided in advance, we do not really need
to decide on α in advance. We can just look at the p-value and see how big it is. Then based on the
following rules, we can determine the strength of evidence against $H_0$ and so in turn, the strength of
evidence to support $H_1$ :
+ If $p > 0.10$, there is very little evidence against $H_0$ or we can say there is no evidence against $H_0$ .
+ If $0.05 < p \leq 0.10$, there is weak evidence against $H_0$ .
+ If $0.01 < p \leq 0.05$, there is evidence against $H_0$ .
+ If $0.001 < p \leq 0.01$, there is strong evidence against $H_0$ .
+ If $p \leq 0.001$, there is very strong evidence against $H_0$ .


* Using critical values for hypothesis testing

There are methods which can be used to decide whether we can reject or not to
reject $H_0$ at some $\alpha$ without finding the exact p-value. A traditional method of hypothesis testing
uses a table of known critical values.

* 
We reject the null hypothesis $H_0$ at the significance level α, depending on $H_1$ , following these
rules (for most parametric tests):

+ If $H_1$ : parameter < hypothesised value, then we reject $H_0$ at $\alpha$, if
  the value of the test statistic is less than (or equal to) the
  critical value at $\alpha$ for the lower tail of the relevant distribution.
+ If $H_1$ : parameter > hypothesised value, then we reject $H_0$ at $\alpha$, if
  the value of the test statistic is greater than (or equal to) the
  critical value at α for the upper tail of the relevant distribution.
+ If $H_1$ : parameter $\neq$ hypothesised value, then we reject $H_0$ at $\alpha$,
  if the value of the test statistic is less than (or equal to) the
  critical value at $\alpha/2$ for the lower tail of the relevant
  distribution or greater than (or equal to) the critical value at $\alpha/2$
  for the upper tail of the relevant distribution.

* Error Types

Remember that we make an inference about population parameters, using a particular sample, and
we do not know the population parameters. We usually do not know whether our inference is correct
or not. In reaching a decision, we may make two types of errors:

+ Type I error: We reject $H_0$ when $H_0$ is in fact true
+ Type II error: We fail to reject $H_0$ when $H_0$ is in fact false.

* Example

A new low cost diagnostic test has been developed that claims to diagnose a particular
medical condition in its early stages. The patient is assumed not to have the condition unless there
is evidence from the test to contradict this. We will discuss Type I and Type II errors in this context
and their consequences. First, we formulate the hypotheses:
+ $H_0$ : The patient does not have the condition.
+ $H_1$ : The patient has the condition.

* ... Example

A Type I error is when the condition is diagnosed in a patient that does not have the condition.
This would result in an expensive treatment being administered, as well as any possible side effects
of such treatment. Note that a Type I error is sometimes referred to as a false positive.
\vspace{0.5cm}


A Type II error is when the condition is not diagnosed in a patient that has the condition. This
could result in the condition progressing and possibly going unnoticed. Note that a Type II error is
sometimes referred to as a false negative.


* Test for a population mean

The underlying assumption for these tests is that the population is normally distributed.
There are two types of tests for a population mean, depending on whether the population variance
$\sigma$ 2 is known or not.

+ If $\sigma$ 2 is known, then we use the Z-test.
+ If $\sigma$ 2 is unknown, then we use the t-test.


* Z-test

+ State hypotheses, the null hypothesis $H_0 : \mu = \mu_0$ and the
  alternative hypothesis $H_1 : \mu < \mu_0$ for the lower tail,
  $H_1 : \mu > \mu_0$ for the upper tail, or $H_1 : \mu = \mu_0$ for
  the two-tailed alternative.

+ Calculate the test statistic
\begin{equation}
Z = \frac{\hat{\theta}-\mu_0}{\sigma/\sqrt{n}}.
\end{equation}

+ Compare the value of the test statistic to the critical value in the
  standard normal distribution tables for the relevant significance
  level, remembering to half the significance level for a two- tailed
  test. Alternatively, compute the p-value.

* 

+ Decide whether to reject or not to reject the null hypothesis at $\alpha$. Remember that $Z \sim N (0, 1)$ and so we use critical values $z_{\alpha}$ or $z_{α/2}$ as following
  + For the alternative $H_1 : \mu < \mu_0$ , we reject $H_0$ at $\alpha$ if $Z < −z_{\alpha}$.
  + For the alternative $H_1 : \mu > \mu_0$ , we reject $H_0$ at $\alpha$ if $Z > z_{\alpha}$.
  + For the alternative $H_1 : \mu \neq \mu_0$ , we reject $H_0$ at $\alpha$ if $|Z| > z_{\alpha/2}$.
  + If we calculate the exact p-value, then, of course, we use general rules: That is if $p \leq \alpha$, then we reject $H_0$ at $\alpha$, otherwise we fail to reject $H_0$ at $\alpha$.

+ Interpret your conclusion practically in the context of the question.


* Example

Cholesterol level in a particular population was known to have a mean value μ = 170
in the past. We also know that the population standard deviation of the cholesterol is σ = 30.
A random sample of n = 20 people was taken and their sample mean was 185. Perform Z-test
to determine whether there is evidence that the population mean has increased. Test at the 5%
significance level. You may assume that the cholesterol level is normally distributed.
\vspace{0.5cm}


Note that we solved this problem before, but this time we solve it without calculating the exact
p-value; we use critical values.


* 

In the tables we look for the critical value at the 5% level, that is z(0.05) = 1.6449. We compare
this with the value of test statistic 2.236. Since $2.236 > 1.6449$, we reject $H_0$ at the 5% level. Note
that since our alternative is $H_1 : \mu > 170$, we used the rejection rule for $H_1 : \mu > \mu_0$ , which is that
we reject $H_0$ at $\alpha$ if $Z > z_{\alpha}$.
\vspace{0.5cm}


There is evidence that mean cholesterol level has increased from 170.

* Exercise

Perform Z-test to
determine whether there is evidence that the population mean differs from 170. You may assume
that the cholesterol level is normally distributed.


* More graphical example

+ Usually have a sample $X_1, X_2, \ldots, X_n$, of size $n$. 
+ We want to perform an hypotesis test for the population mean. 
+ The estimate for the population mean will be denoted by $\hat{\theta}$ or $\hat{\mu}$,
+ The sample variance will be denoted by $\hat{S}^2$.
+ If the Central Limit Theorem applies, we use the $Z-test$, otherwise we use the $t-test$ with $n-1$ degrees of freedom.

* 
** One-sided Hypotesis test
With an $\alpha$ level of confidence, perform the hypotesis test:
\begin{equation}
\begin{split}
H_0 : \mu = \mu_0,\\
H_1 : \mu > \mu_0,
\end{split}
\end{equation}

* 

If we draw the Normal Distribution with $N(\mu_0, \hat{S}/ \sqrt{n})$, and identify our estimate for the mean $\hat{\theta}$:

#+latex: \includegraphics[width = 7cm]{HT_s1.pdf}

* 

The formula : $Z = (\hat{\theta} - \mu_0)/(S/\sqrt{n})$,
 transforms the previous drawing into an equivalent one for the Standard Normal Distribution $N(0,1)$.

#+latex: \includegraphics[width = 7cm]{HT_s2.pdf}


* 

The p-value is the shaded area under the curve (in this case) to the left of $Z$ as shown below

#+latex: \includegraphics[width = 7cm]{HT_s3.pdf}


* 
When we are given the $\alpha$ level (usually 5%), we use it to find the rejection area.
An area equals to the $\alpha$ value, corresponds a $z_{\alpha}$ score

#+latex: \includegraphics[width = 7cm]{HT_s4.pdf}

* 

Then, the following comparisons are related
+ A comparison between the p-value with the $\alpha$ level (comparing areas).
+ A comparison between the statistic $Z$ and the $z_{\alpha}$ (comparing scores).


#+ATTR_LATEX: :environment longtable :align |l|l|l|
|-------------------+---------------------+-----------------------|
| $Z$ vs $z_\alpha$ | p-value vs $\alpha$ | Conclusion            |
|-------------------+---------------------+-----------------------|
| Z > $z_{\alpha}$  | p-value < $\alpha$  | we reject $H_0$       |
|-------------------+---------------------+-----------------------|
| Z < $z_{\alpha}$  | p-value > $\alpha$  | we can't reject $H_0$ |
|-------------------+---------------------+-----------------------|


* Code for the graphs
:PROPERTIES:
:BEAMER_OPT: shrink=50
:END:

#+begin_example R
my_plot1 <- function(x,y,color="#3498db",ylabel="f(x)",xlabel="x",my.title="Plot title",...){
par(family="mono",fg="grey10") 
plot(x,y,
main=my.title,
ylab = ylabel,
xlab = xlabel,
col= color,
type= "l",
lwd="3",...
)
abline(v=x,col="grey80",lty=3)
abline(h=seq(min(y),max(y),length.out=length(x)),col="grey80",lty=3)
abline(v=0,h=0,col="grey10")
}

## I have the previous code in my_Rtools.R and just call
## suorce("./my_Rtools.R")

png("Image_name.png")  ## look aslo at pdf(), jpeg() and other file types. (?png)
XX  <-  seq (-5,5, by= 0.05)
YY  <- dnorm(XX)
my_plot1(XX,YY ,my.title="Hypotesis Test Example", xlabel = " ", xaxt="n", yaxt = "n")
axis(1,labels=FALSE)
abline(v=0, lty=3, col="red", lwd = 3)
axis(1,0,"0",lwd = 3, col = "red")
abline(v=1.8, lty=3, col="orange", lwd = 3)
axis(1,1.8, expression(paste("Z",alpha)),lwd = 3, col = "orange")
polygon(
    c( XX[XX>= 1.8], 1.8),
    c(YY[XX>= 1.8], YY[XX==5]),
    col="yellow")
text(2.03,0.025, expression(alpha))
dev.off()
#+end_example





* References

[1] Slides based on Lecture Notes on "Statistical Theory and Methods 1" at Liverpool University.

[2] Data Analysis Using Regression And Multilevel/Hierarchical Models. Andrew Gelman and Jennifer Hill. Cambridge University Press. 2007.


